---
- name: Install Nginx PKG
  yum:
    name:  "{{ nginx_package }}"
    state: latest
    update_cache: yes
  notify:
    - start_nginx

- name: Update index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner:  "{{ nginx_nobody_user }}"
    group:  "{{ nginx_nobody_group }}"
    mode:  0644
  notify:
    - restart_nginx
  tags:
    - nginx_index_config

