---
- name: grant every host to connection
  shell: |
    source ~/.bash_profile
    ./mysql -uroot -e "use mysql;grant all privileges on *.* to 'root'@'%' identified by '{{ mysql.pass }}' with grant option;flush privileges;"
  args:
    chdir: "{{ mysql.basedir }}/bin"
